apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-corp-app
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::554422868760:role/tomi-eks-corp-platform-app-pod-role